### ISSUE TITLE
Redis return bytes-like object instead of str

### ISSUE THREAD

**Issue by khanek** [ybrs/single-beat#19]
Hi!
When I run code in our environment we have this error:
```
ERROR:tornado.application:Exception in callback <bound method Process.timer_cb of <singlebeat.beat.Process object at 0x7f0f8b7bcdd8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado-5.1.1-py3.6-linux-x86_64.egg/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/usr/local/lib/python3.6/site-packages/single_beat-0.3.0-py3.6.egg/singlebeat/beat.py", line 139, in timer_cb
    fn()
  File "/usr/local/lib/python3.6/site-packages/single_beat-0.3.0-py3.6.egg/singlebeat/beat.py", line 120, in timer_cb_running
    redis_fence_token = rds.get("SINGLE_BEAT_{identifier}".format(identifier=self.identifier)).split(":")[0]
TypeError: a bytes-like object is required, not 'str'
```

I think its probably because `rds.get(...)` function returns bytes instead of str.

**Comment by ybrs** [comment]
@khanek Thanks for reporting the issue. Indeed it was because of bytes, my bad I only tested it with  python2 but on python3 it was causing the issue. Sorry for that.

Anyways, I pushed the fix also updated the package on pypi - also tested with python3 and python2. Please let me know if you see any problems.

By the way, also we need some kind of automated tests in place to prevent this again.

Thank you,
